# MP2 Part 1 — commit retrieval (melawady)
Retrieves every commit for my 10 assigned projects from World of Code, plus stars / forks / last commit date from GitHub.

Commit contents are cached per project in `cache/*.jsonl`, so if the run is interrupted (wandb_client and pytorch_audio are large) just re-run the cells and it resumes where it stopped.

In [ ]:
%pip install -U pandas matplotlib requests tqdm
# python-woc is not used: it only ships Linux builds and fails to compile on Windows
# please clear the output of this cell in your notebook before checking it in

Requirement already satisfied: pandas in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: matplotlib in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.11.2)
Requirement already satisfied: requests in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.34.2)
Requirement already satisfied: tqdm in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (4.70.1)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.66.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: colorama in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\Users\melawady\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
NETID = 'melawady'
PROJECTS = {  # WoC project id -> GitHub repo (from net2prj.csv, netid melawady)
    'nickabattista_ib2d':      'https://github.com/nickabattista/IB2d',
    'cartavis_carta-frontend': 'https://github.com/CARTAvis/carta-frontend',
    'nanocomp_mpb':            'https://github.com/NanoComp/mpb',
    'kklmn_xrt':               'https://github.com/kklmn/xrt',
    'pytorch_audio':           'https://github.com/pytorch/audio',
    'bernatgel_karyoploter':   'https://github.com/bernatgel/karyoploteR',
    'wandb_client':            'https://github.com/wandb/client',
    'ohdsi_atlas':             'https://github.com/OHDSI/Atlas',
    'mummer4_mummer':          'https://github.com/mummer4/mummer',
    'nmslib_nmslib':           'https://github.com/nmslib/nmslib',
}

# Optional: a GitHub personal access token (no scopes needed) raises the GitHub API limit
# from 60 to 5000 requests/hour. Leave empty to go unauthenticated. Don't commit a real token.
GH_TOKEN = ''

## 1. Commit sha1s per project (WoC `p2c` map)

In [ ]:
import os, time, json
import pandas as pd
from tqdm import tqdm
import requests

class WocRemote:
    """Minimal stand-in for woc.remote.WocMapsRemote (same REST calls, same return values).
    python-woc has no Windows builds and needs a C++ compiler to install, so we call the API directly."""
    def __init__(self, base_url='https://worldofcode.org/api', api_key=None):
        self.base_url = base_url.rstrip('/')
        self.s = requests.Session()
        if api_key:
            self.s.headers['Authorization'] = f'Bearer {api_key}'

    def _get(self, path, params=None):
        r = self.s.get(self.base_url + path, params=params, timeout=(30, 180))
        if r.status_code == 429:
            wait = int(r.headers.get('Retry-After', 60))
            time.sleep(wait)  # server asked us to back off
            raise RuntimeError(f'rate limited, waited {wait}s')
        r.raise_for_status()
        return r.json()

    def get_values(self, map_name, key):
        return self._get(f'/lookup/map/{map_name}/{key}')['data']

    def get_values_many(self, map_name, keys):
        j = self._get(f'/lookup/map/{map_name}', params=[('q', k) for k in keys])
        return j['data'], j.get('errors', {})

woc = WocRemote()
# woc = WocRemote(api_key="woc-XXXXXX-YYYYYY")

if os.path.exists('df_commits.csv'):
    df_shas = pd.read_csv('df_commits.csv')
else:
    rows = []
    for prj in PROJECTS:
        shas = woc.get_values('p2c', prj)
        print(f'{prj:26s} {len(shas):6d} commit sha1s')
        rows += [(prj, s) for s in shas]
        time.sleep(1)
    df_shas = pd.DataFrame(rows, columns=['project', 'sha1']).drop_duplicates()
    df_shas.to_csv('df_commits.csv', index=False)

df_shas.groupby('project').size().rename('sha1s')

project
bernatgel_karyoploter        674
cartavis_carta-frontend    12488
kklmn_xrt                   1592
mummer4_mummer               413
nanocomp_mpb                1351
nickabattista_ib2d           994
nmslib_nmslib               1995
ohdsi_atlas                 6665
pytorch_audio              15864
wandb_client               54754
Name: sha1s, dtype: int64

## 2. Commit contents (WoC `commit.tch`), batches of 10 with a 1 s wait between requests

In [ ]:
BATCH = 10   # README: keep chunks well under 50 and wait between requests
os.makedirs('cache', exist_ok=True)

def fetch_batch(batch, tries=25):
    # WoC is often overloaded (everyone in the class hits it at once): keep retrying for a long time
    for attempt in range(tries):
        try:
            res, err = woc.get_values_many('commit.tch', batch)
            return {k: v[0] for k, v in res.items()}, err
        except Exception as e:
            wait = min(300, 10 * 2 ** attempt)
            print(f'  request failed ({type(e).__name__}: {str(e)[:120]}); retry {attempt + 1}/{tries} in {wait}s')
            time.sleep(wait)
    raise RuntimeError('giving up on a batch - re-run this cell later to resume')

for prj, grp in df_shas.groupby('project'):
    path = f'cache/{prj}.jsonl'
    done = set()
    if os.path.exists(path):
        with open(path, encoding='utf-8') as f:
            done = {json.loads(line)['commit'] for line in f}
    todo = [s for s in grp['sha1'] if s not in done]
    print(f'{prj}: {len(done)} cached, {len(todo)} to fetch')
    with open(path, 'a', encoding='utf-8') as out:
        for i in tqdm(range(0, len(todo), BATCH), desc=prj):
            res, err = fetch_batch(todo[i:i + BATCH])
            if err:
                print('  WoC reported errors:', err)
            for sha, c in res.items():
                # c = [tree, [parents], [author, unixtime, tz], [committer, unixtime, tz], message]
                out.write(json.dumps({'project': prj, 'commit': sha, 'author': c[2][0],
                                      'time': int(c[2][1]), 'message': c[4]}) + '\n')
            out.flush()
            time.sleep(1)

bernatgel_karyoploter: 674 cached, 0 to fetch

bernatgel_karyoploter: 0it [00:00, ?it/s]

cartavis_carta-frontend: 740 cached, 11748 to fetch

cartavis_carta-frontend:   9%|▉         | 106/1175 [01:49<18:35,  1.04s/it]

  WoC reported errors: {'24a6bc650d2911ac890056402dc90f9745d995b9': 'Key 24a6bc650d2911ac890056402dc90f9745d995b9 not found in /da5_fast/All.sha1c/commit_36.tch'}

cartavis_carta-frontend:  10%|█         | 120/1175 [02:04<18:11,  1.03s/it]

  WoC reported errors: {'27b54bf656881764e13ede34e08194c18ebf1133': 'Key 27b54bf656881764e13ede34e08194c18ebf1133 not found in /da5_fast/All.sha1c/commit_39.tch'}

cartavis_carta-frontend:  14%|█▍        | 165/1175 [02:50<17:25,  1.03s/it]

  WoC reported errors: {'31860edaced35fa0bb95e4a398479b63a62b03d3': 'Key 31860edaced35fa0bb95e4a398479b63a62b03d3 not found in /da5_fast/All.sha1c/commit_49.tch'}

cartavis_carta-frontend:  47%|████▋     | 549/1175 [09:28<10:46,  1.03s/it]

  WoC reported errors: {'81ec31ae41568e463ae73f20d260397ce2b6feca': 'Key 81ec31ae41568e463ae73f20d260397ce2b6feca not found in /da5_fast/All.sha1c/commit_1.tch'}

cartavis_carta-frontend:  48%|████▊     | 568/1175 [09:47<10:28,  1.03s/it]

  WoC reported errors: {'85d01d0a361d8d7721467f789628e21275b25f08': 'Key 85d01d0a361d8d7721467f789628e21275b25f08 not found in /da5_fast/All.sha1c/commit_5.tch'}

cartavis_carta-frontend:  53%|█████▎    | 622/1175 [10:43<09:30,  1.03s/it]

  WoC reported errors: {'90a6907b18bac9054ea5f1c632c4ed0d630e7f9a': 'Key 90a6907b18bac9054ea5f1c632c4ed0d630e7f9a not found in /da5_fast/All.sha1c/commit_16.tch'}

cartavis_carta-frontend:  59%|█████▉    | 692/1175 [11:55<08:17,  1.03s/it]

  WoC reported errors: {'9e802a802d8d14df56e3ef2085f7cf4aeed5d1e4': 'Key 9e802a802d8d14df56e3ef2085f7cf4aeed5d1e4 not found in /da5_fast/All.sha1c/commit_30.tch'}

cartavis_carta-frontend:  62%|██████▏   | 729/1175 [12:33<07:39,  1.03s/it]

  WoC reported errors: {'a659e2f21751a910a63280eed6aebf8a2c78159d': 'Key a659e2f21751a910a63280eed6aebf8a2c78159d not found in /da5_fast/All.sha1c/commit_38.tch', 'a65b211e7bc22ec8aaa49b1503ca0e3620d7029a': 'Key a65b211e7bc22ec8aaa49b1503ca0e3620d7029a not found in /da5_fast/All.sha1c/commit_38.tch'}

cartavis_carta-frontend:  71%|███████   | 831/1175 [14:18<05:54,  1.03s/it]

  WoC reported errors: {'bb12fa2f9774a2672d96984591118affe98c5a1f': 'Key bb12fa2f9774a2672d96984591118affe98c5a1f not found in /da5_fast/All.sha1c/commit_59.tch'}

cartavis_carta-frontend:  80%|████████  | 941/1175 [16:12<04:01,  1.03s/it]

  WoC reported errors: {'d122b15881f08e924ed1c79bee2d0d048c785c5e': 'Key d122b15881f08e924ed1c79bee2d0d048c785c5e not found in /da5_fast/All.sha1c/commit_81.tch'}

cartavis_carta-frontend:  83%|████████▎ | 970/1175 [16:42<03:32,  1.04s/it]

  WoC reported errors: {'d73a5f78d963898b60a3d21d40fb6153e71a24c6': 'Key d73a5f78d963898b60a3d21d40fb6153e71a24c6 not found in /da5_fast/All.sha1c/commit_87.tch', 'd740f56c61d64a2e64b458e2f0de5be2eaae7b6e': 'Key d740f56c61d64a2e64b458e2f0de5be2eaae7b6e not found in /da5_fast/All.sha1c/commit_87.tch'}

cartavis_carta-frontend:  91%|█████████ | 1072/1175 [18:28<01:46,  1.03s/it]

  WoC reported errors: {'eb7bcd02f256222239cc4c6fea6c9e1bce88fef4': 'Key eb7bcd02f256222239cc4c6fea6c9e1bce88fef4 not found in /da5_fast/All.sha1c/commit_107.tch'}

cartavis_carta-frontend: 100%|██████████| 1175/1175 [20:14<00:00,  1.03s/it]

kklmn_xrt: 0 cached, 1592 to fetch

kklmn_xrt:  90%|█████████ | 144/160 [02:26<00:16,  1.01s/it]

  WoC reported errors: {'e87c18b6e12c0057ed7110e781aa1ecb997cb87e': 'Key e87c18b6e12c0057ed7110e781aa1ecb997cb87e not found in /da5_fast/All.sha1c/commit_104.tch'}

kklmn_xrt: 100%|██████████| 160/160 [02:42<00:00,  1.02s/it]

mummer4_mummer: 0 cached, 413 to fetch

mummer4_mummer:   5%|▍         | 2/42 [00:02<00:40,  1.01s/it]

  WoC reported errors: {'104981b04e9e01943c324793e4100ddd1495a3a6': 'Key 104981b04e9e01943c324793e4100ddd1495a3a6 not found in /da5_fast/All.sha1c/commit_16.tch'}

mummer4_mummer:  17%|█▋        | 7/42 [00:07<00:35,  1.01s/it]

  WoC reported errors: {'342c65c23fff37e66617a2c0e13bbc3d6d9d66b9': 'Key 342c65c23fff37e66617a2c0e13bbc3d6d9d66b9 not found in /da5_fast/All.sha1c/commit_52.tch'}

mummer4_mummer:  50%|█████     | 21/42 [00:21<00:21,  1.01s/it]

  WoC reported errors: {'8917debe962e1a3f570dd0de38dabc6140735187': 'Key 8917debe962e1a3f570dd0de38dabc6140735187 not found in /da5_fast/All.sha1c/commit_9.tch'}

mummer4_mummer:  55%|█████▍    | 23/42 [00:23<00:19,  1.01s/it]

  WoC reported errors: {'94a1f773e70062f87c242923bb301d5f547940ea': 'Key 94a1f773e70062f87c242923bb301d5f547940ea not found in /da5_fast/All.sha1c/commit_20.tch'}

mummer4_mummer:  57%|█████▋    | 24/42 [00:24<00:18,  1.01s/it]

  WoC reported errors: {'977d4b519fc8a45e6c5bb001b15b8bc977763cef': 'Key 977d4b519fc8a45e6c5bb001b15b8bc977763cef not found in /da5_fast/All.sha1c/commit_23.tch'}

mummer4_mummer:  88%|████████▊ | 37/42 [00:37<00:05,  1.02s/it]

  WoC reported errors: {'e97ae1e0faf409d2d5b37a0d87c8e688d06995cc': 'Key e97ae1e0faf409d2d5b37a0d87c8e688d06995cc not found in /da5_fast/All.sha1c/commit_105.tch', 'e9a35c5b44a019a249ef022ee9170fb75ca349cd': 'Key e9a35c5b44a019a249ef022ee9170fb75ca349cd not found in /da5_fast/All.sha1c/commit_105.tch'}

mummer4_mummer:  90%|█████████ | 38/42 [00:38<00:04,  1.02s/it]

  WoC reported errors: {'eed34e1ce4b3382ae5091bb6fc99cc2b7510697c': 'Key eed34e1ce4b3382ae5091bb6fc99cc2b7510697c not found in /da5_fast/All.sha1c/commit_110.tch'}

mummer4_mummer: 100%|██████████| 42/42 [00:42<00:00,  1.02s/it]

nanocomp_mpb: 0 cached, 1351 to fetch

nanocomp_mpb:   4%|▍         | 6/136 [00:06<02:11,  1.01s/it]

  WoC reported errors: {'0bb4ab025cf75eb2fb255d2ae72b6c7f7ed4187a': 'Key 0bb4ab025cf75eb2fb255d2ae72b6c7f7ed4187a not found in /da5_fast/All.sha1c/commit_11.tch', '0cb2d3d3ed972221e9ca3c60d794b64f696b5908': 'Key 0cb2d3d3ed972221e9ca3c60d794b64f696b5908 not found in /da5_fast/All.sha1c/commit_12.tch'}

nanocomp_mpb:  28%|██▊       | 38/136 [00:38<01:39,  1.02s/it]

  WoC reported errors: {'483509bdb0c361a0efc46f223756da419665391c': 'Key 483509bdb0c361a0efc46f223756da419665391c not found in /da5_fast/All.sha1c/commit_72.tch'}

nanocomp_mpb:  30%|███       | 41/136 [00:41<01:36,  1.01s/it]

  WoC reported errors: {'4ee1954aeeec0ee8614039e9c83d69bace7b110d': 'Key 4ee1954aeeec0ee8614039e9c83d69bace7b110d not found in /da5_fast/All.sha1c/commit_78.tch'}

nanocomp_mpb:  32%|███▏      | 43/136 [00:43<01:34,  1.02s/it]

  WoC reported errors: {'51f65f17611d415b999678003af3b6667ca27b27': 'Key 51f65f17611d415b999678003af3b6667ca27b27 not found in /da5_fast/All.sha1c/commit_81.tch', '52aa647926a2a1e81cd82f32797792e71a49e7f2': 'Key 52aa647926a2a1e81cd82f32797792e71a49e7f2 not found in /da5_fast/All.sha1c/commit_82.tch'}

nanocomp_mpb:  49%|████▉     | 67/136 [01:08<01:10,  1.02s/it]

  WoC reported errors: {'7d4c72627fc14a370b6776f19751a5ee1392ad1d': 'Key 7d4c72627fc14a370b6776f19751a5ee1392ad1d not found in /da5_fast/All.sha1c/commit_125.tch'}

nanocomp_mpb:  52%|█████▏    | 71/136 [01:12<01:06,  1.02s/it]

  WoC reported errors: {'858a25293c30822deb763ee2601da976a7e5f196': 'Key 858a25293c30822deb763ee2601da976a7e5f196 not found in /da5_fast/All.sha1c/commit_5.tch'}

nanocomp_mpb:  60%|█████▉    | 81/136 [01:22<00:55,  1.01s/it]

  WoC reported errors: {'98969233bdce30f48f1526fd15a42fbd59a7c3c4': 'Key 98969233bdce30f48f1526fd15a42fbd59a7c3c4 not found in /da5_fast/All.sha1c/commit_24.tch'}

nanocomp_mpb:  62%|██████▎   | 85/136 [01:26<00:51,  1.02s/it]

  WoC reported errors: {'a327ee1aba81e259fc5d3a00212bd25c4b398c2a': 'Key a327ee1aba81e259fc5d3a00212bd25c4b398c2a not found in /da5_fast/All.sha1c/commit_35.tch'}

nanocomp_mpb:  68%|██████▊   | 92/136 [01:33<00:44,  1.02s/it]

  WoC reported errors: {'b466b80eb93851f73b88cd4870d425a730509770': 'Key b466b80eb93851f73b88cd4870d425a730509770 not found in /da5_fast/All.sha1c/commit_52.tch'}

nanocomp_mpb:  79%|███████▉  | 108/136 [01:49<00:28,  1.02s/it]

  WoC reported errors: {'d3a0afbb71aeac3710392aa8650b47c8252166e8': 'Key d3a0afbb71aeac3710392aa8650b47c8252166e8 not found in /da5_fast/All.sha1c/commit_83.tch'}

nanocomp_mpb:  84%|████████▍ | 114/136 [01:55<00:22,  1.02s/it]

  WoC reported errors: {'dde4e3d6cd61ac45d34a0dbe1ccf9c2654d20517': 'Key dde4e3d6cd61ac45d34a0dbe1ccf9c2654d20517 not found in /da5_fast/All.sha1c/commit_93.tch'}

nanocomp_mpb:  85%|████████▌ | 116/136 [01:57<00:20,  1.02s/it]

  WoC reported errors: {'e087a2b57dfde691161363d0956e8f75c7b7c90d': 'Key e087a2b57dfde691161363d0956e8f75c7b7c90d not found in /da5_fast/All.sha1c/commit_96.tch'}

nanocomp_mpb:  91%|█████████ | 124/136 [02:06<00:12,  1.01s/it]

  WoC reported errors: {'ef91373c37b9a1d3ef25831f305d820933ccf700': 'Key ef91373c37b9a1d3ef25831f305d820933ccf700 not found in /da5_fast/All.sha1c/commit_111.tch'}

nanocomp_mpb:  96%|█████████▌| 130/136 [02:12<00:06,  1.01s/it]

  WoC reported errors: {'f764c0786c10518af2e36928b07dcbfd0dd1f8f1': 'Key f764c0786c10518af2e36928b07dcbfd0dd1f8f1 not found in /da5_fast/All.sha1c/commit_119.tch'}

nanocomp_mpb: 100%|██████████| 136/136 [02:18<00:00,  1.02s/it]

nickabattista_ib2d: 0 cached, 994 to fetch

nickabattista_ib2d: 100%|██████████| 100/100 [01:41<00:00,  1.02s/it]

nmslib_nmslib: 0 cached, 1995 to fetch

nmslib_nmslib: 100%|██████████| 200/200 [03:23<00:00,  1.02s/it]

ohdsi_atlas: 0 cached, 6665 to fetch

ohdsi_atlas:   1%|          | 5/667 [00:05<11:12,  1.02s/it]

  WoC reported errors: {'01fbfe159482f0f942d5a527834f25d0bd240760': 'Key 01fbfe159482f0f942d5a527834f25d0bd240760 not found in /da5_fast/All.sha1c/commit_1.tch'}

ohdsi_atlas:   1%|          | 7/667 [00:07<11:11,  1.02s/it]

  WoC reported errors: {'02ba46d08832d836652a2d8b00c76cf72d69a26d': 'Key 02ba46d08832d836652a2d8b00c76cf72d69a26d not found in /da5_fast/All.sha1c/commit_2.tch'}

ohdsi_atlas:   1%|▏         | 9/667 [00:09<11:08,  1.02s/it]

  WoC reported errors: {'04008e34da0de4c065586f3aa764777c99da21d1': 'Key 04008e34da0de4c065586f3aa764777c99da21d1 not found in /da5_fast/All.sha1c/commit_4.tch'}

ohdsi_atlas:  14%|█▍        | 93/667 [01:34<09:42,  1.01s/it]

  WoC reported errors: {'24f71a40c4efeccff01f11fde0f2401814bfa7e7': 'Key 24f71a40c4efeccff01f11fde0f2401814bfa7e7 not found in /da5_fast/All.sha1c/commit_36.tch'}

ohdsi_atlas:  16%|█▌        | 106/667 [01:47<09:29,  1.01s/it]

  WoC reported errors: {'29d9d024fb6894453e6dc80e220f5d74cec526f6': 'Key 29d9d024fb6894453e6dc80e220f5d74cec526f6 not found in /da5_fast/All.sha1c/commit_41.tch'}

ohdsi_atlas:  16%|█▋        | 110/667 [01:51<09:26,  1.02s/it]

  WoC reported errors: {'2b32eb544c05bb48e8d96c4d973f9773bbd2b1e1': 'Key 2b32eb544c05bb48e8d96c4d973f9773bbd2b1e1 not found in /da5_fast/All.sha1c/commit_43.tch'}

ohdsi_atlas:  17%|█▋        | 111/667 [01:52<09:25,  1.02s/it]

  WoC reported errors: {'2b708ba80abdc240d5865d3ab655181846612514': 'Key 2b708ba80abdc240d5865d3ab655181846612514 not found in /da5_fast/All.sha1c/commit_43.tch'}

ohdsi_atlas:  18%|█▊        | 121/667 [02:02<09:15,  1.02s/it]

  WoC reported errors: {'2f969408bbb59ea4a51eef98425155e090957df2': 'Key 2f969408bbb59ea4a51eef98425155e090957df2 not found in /da5_fast/All.sha1c/commit_47.tch'}

ohdsi_atlas:  19%|█▊        | 124/667 [02:05<09:11,  1.02s/it]

  WoC reported errors: {'3069bc6df013a2eb22a5c64a9390d070bba8bdf4': 'Key 3069bc6df013a2eb22a5c64a9390d070bba8bdf4 not found in /da5_fast/All.sha1c/commit_48.tch'}

ohdsi_atlas:  20%|██        | 135/667 [02:17<09:06,  1.03s/it]

  WoC reported errors: {'34a0c7a24320f952f9bbf93b2ce0fbc3e048fd34': 'Key 34a0c7a24320f952f9bbf93b2ce0fbc3e048fd34 not found in /da5_fast/All.sha1c/commit_52.tch'}

ohdsi_atlas:  22%|██▏       | 149/667 [02:31<08:54,  1.03s/it]

  WoC reported errors: {'3936fba5bbfc0db985d0ff01822c4380a62d5056': 'Key 3936fba5bbfc0db985d0ff01822c4380a62d5056 not found in /da5_fast/All.sha1c/commit_57.tch'}

ohdsi_atlas:  23%|██▎       | 154/667 [02:36<08:42,  1.02s/it]

  WoC reported errors: {'3b2c19a925221ac73f2e659c505d55ac6c27133c': 'Key 3b2c19a925221ac73f2e659c505d55ac6c27133c not found in /da5_fast/All.sha1c/commit_59.tch'}

ohdsi_atlas:  26%|██▌       | 175/667 [02:58<08:19,  1.02s/it]

  WoC reported errors: {'43200b503e0f15a787ebfcdd7d0f86309ce02bb2': 'Key 43200b503e0f15a787ebfcdd7d0f86309ce02bb2 not found in /da5_fast/All.sha1c/commit_67.tch'}

ohdsi_atlas:  37%|███▋      | 244/667 [04:08<07:09,  1.01s/it]

  WoC reported errors: {'5cc708fb8e3f9e9cdc61a8a8feff437ed1124f2a': 'Key 5cc708fb8e3f9e9cdc61a8a8feff437ed1124f2a not found in /da5_fast/All.sha1c/commit_92.tch'}

ohdsi_atlas:  38%|███▊      | 253/667 [04:17<07:00,  1.01s/it]

  WoC reported errors: {'609bd4b27de893d3e875428c2b7c5af5bd01aff6': 'Key 609bd4b27de893d3e875428c2b7c5af5bd01aff6 not found in /da5_fast/All.sha1c/commit_96.tch'}

ohdsi_atlas:  39%|███▊      | 257/667 [04:21<06:56,  1.02s/it]

  WoC reported errors: {'61a5c443f73985574a0c91b1d5e5874d87a4ddf1': 'Key 61a5c443f73985574a0c91b1d5e5874d87a4ddf1 not found in /da5_fast/All.sha1c/commit_97.tch'}

ohdsi_atlas:  46%|████▌     | 305/667 [05:10<06:07,  1.02s/it]

  WoC reported errors: {'744daf66fa95aedcc23d578b7ad12e1754514638': 'Key 744daf66fa95aedcc23d578b7ad12e1754514638 not found in /da5_fast/All.sha1c/commit_116.tch'}

ohdsi_atlas:  48%|████▊     | 322/667 [05:27<05:52,  1.02s/it]

  WoC reported errors: {'7b1fb3e47e5382e2fb42b89e9c7642226447b2e9': 'Key 7b1fb3e47e5382e2fb42b89e9c7642226447b2e9 not found in /da5_fast/All.sha1c/commit_123.tch'}

ohdsi_atlas:  53%|█████▎    | 353/667 [05:58<05:19,  1.02s/it]

  WoC reported errors: {'8740a845e19156b2ee53bf868b3a506f0c194e99': 'Key 8740a845e19156b2ee53bf868b3a506f0c194e99 not found in /da5_fast/All.sha1c/commit_7.tch'}

ohdsi_atlas:  62%|██████▏   | 416/667 [07:03<04:18,  1.03s/it]

  WoC reported errors: {'9e42fd98c5d29e929b0242ded1eb8aa9e29d3b41': 'Key 9e42fd98c5d29e929b0242ded1eb8aa9e29d3b41 not found in /da5_fast/All.sha1c/commit_30.tch'}

ohdsi_atlas:  65%|██████▌   | 436/667 [07:24<03:58,  1.03s/it]

  WoC reported errors: {'a66bf7a43e2a1bbd53ce6c347f85f18d4418d4a6': 'Key a66bf7a43e2a1bbd53ce6c347f85f18d4418d4a6 not found in /da5_fast/All.sha1c/commit_38.tch'}

ohdsi_atlas:  67%|██████▋   | 450/667 [07:38<03:43,  1.03s/it]

  WoC reported errors: {'aafd0220e7b36b70cfb0751e8ccb26b44b501ce8': 'Key aafd0220e7b36b70cfb0751e8ccb26b44b501ce8 not found in /da5_fast/All.sha1c/commit_42.tch'}

ohdsi_atlas:  72%|███████▏  | 479/667 [08:08<03:13,  1.03s/it]

  WoC reported errors: {'b56fe292ed832c7bde25c1c0e652a11abd00a9c6': 'Key b56fe292ed832c7bde25c1c0e652a11abd00a9c6 not found in /da5_fast/All.sha1c/commit_53.tch'}

ohdsi_atlas:  82%|████████▏ | 546/667 [09:17<02:04,  1.03s/it]

  WoC reported errors: {'cf64c4d6f4d037f4a2d2e1ad27f17bf71a77edee': 'Key cf64c4d6f4d037f4a2d2e1ad27f17bf71a77edee not found in /da5_fast/All.sha1c/commit_79.tch'}

ohdsi_atlas:  84%|████████▍ | 559/667 [09:30<01:51,  1.03s/it]

  WoC reported errors: {'d53c8c5de1d66a459c079150bfc0c907f35b67d7': 'Key d53c8c5de1d66a459c079150bfc0c907f35b67d7 not found in /da5_fast/All.sha1c/commit_85.tch'}

ohdsi_atlas:  87%|████████▋ | 580/667 [09:52<01:29,  1.03s/it]

  WoC reported errors: {'dc93b1b255e0ce5fc45ad798e53522117c10f35c': 'Key dc93b1b255e0ce5fc45ad798e53522117c10f35c not found in /da5_fast/All.sha1c/commit_92.tch'}

ohdsi_atlas:  94%|█████████▎| 625/667 [10:38<00:43,  1.03s/it]

  WoC reported errors: {'eef6a5a60a022d3acb2902489a0270cbc39fecb6': 'Key eef6a5a60a022d3acb2902489a0270cbc39fecb6 not found in /da5_fast/All.sha1c/commit_110.tch'}

ohdsi_atlas:  95%|█████████▍| 631/667 [10:44<00:37,  1.03s/it]

  WoC reported errors: {'f19e7737f1a92dd0979bdc88b2591d1dfd6f2654': 'Key f19e7737f1a92dd0979bdc88b2591d1dfd6f2654 not found in /da5_fast/All.sha1c/commit_113.tch'}

ohdsi_atlas: 100%|█████████▉| 665/667 [11:19<00:02,  1.03s/it]

  WoC reported errors: {'ffaca48a7997bf7e3784e3293dd61766fd15aac2': 'Key ffaca48a7997bf7e3784e3293dd61766fd15aac2 not found in /da5_fast/All.sha1c/commit_127.tch'}

ohdsi_atlas: 100%|██████████| 667/667 [11:21<00:00,  1.02s/it]

pytorch_audio: 0 cached, 15864 to fetch

pytorch_audio:  17%|█▋        | 265/1587 [04:34<22:52,  1.04s/it]

  WoC reported errors: {'2a6a096d3c7444024cde2dc685231459064a9a19': 'Key 2a6a096d3c7444024cde2dc685231459064a9a19 not found in /da5_fast/All.sha1c/commit_42.tch'}

pytorch_audio:  50%|████▉     | 792/1587 [13:39<13:42,  1.03s/it]

  WoC reported errors: {'7f5e1ad5e87eef31120ede5a6bcb23c606ad745f': 'Key 7f5e1ad5e87eef31120ede5a6bcb23c606ad745f not found in /da5_fast/All.sha1c/commit_127.tch'}

pytorch_audio:  58%|█████▊    | 920/1587 [15:52<11:27,  1.03s/it]

  WoC reported errors: {'93fad02e7a2d02ade6f5590206b6946d3fc90caa': 'Key 93fad02e7a2d02ade6f5590206b6946d3fc90caa not found in /da5_fast/All.sha1c/commit_19.tch'}

pytorch_audio:  61%|██████    | 972/1587 [16:46<10:38,  1.04s/it]

  WoC reported errors: {'9c346f57f26d7529b552106d8e1d54793308f6e8': 'Key 9c346f57f26d7529b552106d8e1d54793308f6e8 not found in /da5_fast/All.sha1c/commit_28.tch'}

pytorch_audio:  79%|███████▉  | 1256/1587 [21:39<05:41,  1.03s/it]

  WoC reported errors: {'ca00f8a4d36f964c6460590f0b43231c541a242e': 'Key ca00f8a4d36f964c6460590f0b43231c541a242e not found in /da5_fast/All.sha1c/commit_74.tch'}

pytorch_audio:  91%|█████████ | 1438/1587 [24:48<02:34,  1.03s/it]

  WoC reported errors: {'e7efdd129c79a306e9cfe16ffbca6b059909c6c0': 'Key e7efdd129c79a306e9cfe16ffbca6b059909c6c0 not found in /da5_fast/All.sha1c/commit_103.tch'}

pytorch_audio:  94%|█████████▎| 1487/1587 [25:38<01:43,  1.03s/it]

  WoC reported errors: {'f0271cd5a647e873215f847a4694b889c8c311fa': 'Key f0271cd5a647e873215f847a4694b889c8c311fa not found in /da5_fast/All.sha1c/commit_112.tch'}

pytorch_audio:  99%|█████████▉| 1574/1587 [27:08<00:13,  1.03s/it]

  WoC reported errors: {'fe2735baf3561b7c43747d5dfe20d5c8a568fe58': 'Key fe2735baf3561b7c43747d5dfe20d5c8a568fe58 not found in /da5_fast/All.sha1c/commit_126.tch'}

pytorch_audio: 100%|██████████| 1587/1587 [27:22<00:00,  1.03s/it]

wandb_client: 0 cached, 54754 to fetch

wandb_client:   1%|          | 46/5476 [00:47<1:33:38,  1.03s/it]

  WoC reported errors: {'025031ec04baf1d1a6bc42ac8b431e635b39adcd': 'Key 025031ec04baf1d1a6bc42ac8b431e635b39adcd not found in /da5_fast/All.sha1c/commit_2.tch'}

wandb_client:   6%|▋         | 354/5476 [06:05<1:27:59,  1.03s/it]

  WoC reported errors: {'10a3ea4ba74344e6c20ab9f3fe87a88a05bf3325': 'Key 10a3ea4ba74344e6c20ab9f3fe87a88a05bf3325 not found in /da5_fast/All.sha1c/commit_16.tch'}

wandb_client:  12%|█▏        | 676/5476 [11:39<1:22:43,  1.03s/it]

  WoC reported errors: {'1fd95b30eb146339b454d264a88535247da4aa57': 'Key 1fd95b30eb146339b454d264a88535247da4aa57 not found in /da5_fast/All.sha1c/commit_31.tch'}

wandb_client:  20%|██        | 1111/5476 [19:09<1:15:16,  1.03s/it]

  WoC reported errors: {'33fb62c393a894fd9aad139bdcbbf315d1987cc0': 'Key 33fb62c393a894fd9aad139bdcbbf315d1987cc0 not found in /da5_fast/All.sha1c/commit_51.tch'}

wandb_client:  23%|██▎       | 1234/5476 [21:16<1:13:05,  1.03s/it]

  WoC reported errors: {'396f0d2da27e99af0367048f2f96eea947c17463': 'Key 396f0d2da27e99af0367048f2f96eea947c17463 not found in /da5_fast/All.sha1c/commit_57.tch'}

wandb_client:  26%|██▌       | 1437/5476 [24:47<1:09:49,  1.04s/it]

  WoC reported errors: {'431b91b5eb3db801794b68b1e6a9fea85435950c': 'Key 431b91b5eb3db801794b68b1e6a9fea85435950c not found in /da5_fast/All.sha1c/commit_67.tch'}

wandb_client:  27%|██▋       | 1457/5476 [25:07<1:09:14,  1.03s/it]

  WoC reported errors: {'440c2fada2c43d2b22b3542006b1d9e384a4d0bc': 'Key 440c2fada2c43d2b22b3542006b1d9e384a4d0bc not found in /da5_fast/All.sha1c/commit_68.tch'}

wandb_client:  30%|███       | 1669/5476 [28:47<1:05:39,  1.03s/it]

  WoC reported errors: {'4e29ea422aaa3e8e1101824a946e0bb499e37556': 'Key 4e29ea422aaa3e8e1101824a946e0bb499e37556 not found in /da5_fast/All.sha1c/commit_78.tch'}

wandb_client:  54%|█████▍    | 2970/5476 [51:13<43:04,  1.03s/it]

  WoC reported errors: {'8a6d19413e5f1e548f0aa0cac41a24d8ddead17e': 'Key 8a6d19413e5f1e548f0aa0cac41a24d8ddead17e not found in /da5_fast/All.sha1c/commit_10.tch'}

wandb_client:  62%|██████▏   | 3399/5476 [58:37<35:45,  1.03s/it]

  WoC reported errors: {'9ef76c176de76902e27e1a8eecf68032d75c306d': 'Key 9ef76c176de76902e27e1a8eecf68032d75c306d not found in /da5_fast/All.sha1c/commit_30.tch'}

wandb_client:  81%|████████▏ | 4459/5476 [1:16:52<17:29,  1.03s/it]

  WoC reported errors: {'d0b437efc86a38c39858db8b2f5b0aa34be00412': 'Key d0b437efc86a38c39858db8b2f5b0aa34be00412 not found in /da5_fast/All.sha1c/commit_80.tch'}

wandb_client:  89%|████████▊ | 4859/5476 [1:23:45<10:36,  1.03s/it]

  WoC reported errors: {'e38f2ed3b43185617dd1c49bf24d51a6f6cce0db': 'Key e38f2ed3b43185617dd1c49bf24d51a6f6cce0db not found in /da5_fast/All.sha1c/commit_99.tch'}

wandb_client: 100%|██████████| 5476/5476 [1:34:23<00:00,  1.03s/it]

## 3. Write `melawady_project_summary.csv` (semicolon separated) and validate counts

In [ ]:
recs = []
for prj in PROJECTS:
    with open(f'cache/{prj}.jsonl', encoding='utf-8') as f:
        recs += [json.loads(line) for line in f]

summary = (pd.DataFrame(recs)
             .drop_duplicates(['project', 'commit'])
             .rename(columns={'project': 'project_wocid', 'commit': 'commit_sha1', 'message': 'commit message'})
             [['project_wocid', 'commit_sha1', 'author', 'time', 'commit message']]
             .sort_values(['project_wocid', 'time']))
summary.to_csv(f'{NETID}_project_summary.csv', sep=';', index=False)

# validation: every sha1 from p2c should have content
check = (df_shas.groupby('project').size().rename('p2c_sha1s').to_frame()
         .join(summary.groupby('project_wocid').size().rename('retrieved')))
check['missing'] = check['p2c_sha1s'] - check['retrieved']
check

                         p2c_sha1s  retrieved  missing
project
bernatgel_karyoploter          674        674        0
cartavis_carta-frontend      12488      12474       14
kklmn_xrt                     1592       1591        1
mummer4_mummer                 413        405        8
nanocomp_mpb                  1351       1335       16
nickabattista_ib2d             994        994        0
nmslib_nmslib                 1995       1995        0
ohdsi_atlas                   6665       6636       29
pytorch_audio                15864      15856        8
wandb_client                 54754      54742       12

## 4. WoC statistics per project

In [ ]:
woc_stats = summary.groupby('project_wocid').agg(
    ncommits=('commit_sha1', 'nunique'),
    nauthors=('author', 'nunique'),
    min_time=('time', 'min'),
    max_time=('time', 'max'))
woc_stats['min_date'] = pd.to_datetime(woc_stats['min_time'], unit='s').dt.strftime('%Y-%m-%d')
woc_stats['max_date'] = pd.to_datetime(woc_stats['max_time'], unit='s').dt.strftime('%Y-%m-%d')
woc_stats.to_csv(f'{NETID}_woc_stats.csv', sep=';')
woc_stats

,ncommits,nauthors,min_time,max_time,min_date,max_date
project_wocid,,,,,,
bernatgel_karyoploter,674,15,1444405906,1749198667,2015-10-09,2025-06-06
cartavis_carta-frontend,12474,76,1524835993,1762270305,2018-04-27,2025-11-04
kklmn_xrt,1591,12,1459266517,1762357339,2016-03-29,2025-11-05
mummer4_mummer,405,29,1352343979,1739151225,2012-11-08,2025-02-10
nanocomp_mpb,1335,35,895645130,1775155248,1998-05-20,2026-04-02
nickabattista_ib2d,994,28,1434499605,1756008042,2015-06-17,2025-08-24
nmslib_nmslib,1995,100,1373454367,1776120170,2013-07-10,2026-04-13
ohdsi_atlas,6636,139,1436372795,1761750248,2015-07-08,2025-10-29
pytorch_audio,15856,1513,1493944663,1776253805,2017-05-05,2026-04-15
wandb_client,54742,561,1487661941,1762386331,2017-02-21,2025-11-05

## 5. GitHub statistics (stars, forks, last commit date on the default branch)
Also saves the 10 most recent GitHub commits per project, used for `RecentThemes` in Part 3.

In [ ]:
import requests

H = {'Accept': 'application/vnd.github+json'}
if GH_TOKEN:
    H['Authorization'] = f'Bearer {GH_TOKEN}'

def gh(url):
    r = requests.get(url, headers=H, timeout=30)
    r.raise_for_status()
    return r.json()

gh_rows, recent = [], []
for prj, url in PROJECTS.items():
    full = url.rstrip('/').split('github.com/')[1]
    try:
        repo = gh(f'https://api.github.com/repos/{full}')          # follows renamed/transferred repos
        commits = gh(f"https://api.github.com/repos/{repo['full_name']}/commits"
                     f"?sha={repo['default_branch']}&per_page=10")
        gh_rows.append({'project': prj, 'gh_full_name': repo['full_name'],
                        'nstars': repo['stargazers_count'], 'nforks': repo['forks_count'],
                        'lastGHCommitDate': commits[0]['commit']['committer']['date'][:10],
                        'archived': repo['archived']})
        for c in commits:
            recent.append({'project': prj, 'commit_sha1': c['sha'],
                           'author': f"{c['commit']['author']['name']} <{c['commit']['author']['email']}>",
                           'date': c['commit']['author']['date'], 'commit message': c['commit']['message']})
    except Exception as e:
        print(f'{prj}: GitHub lookup failed ({e}). Check {url} in a browser and fill in by hand.')
        gh_rows.append({'project': prj})
    time.sleep(1)

gh_stats = pd.DataFrame(gh_rows).set_index('project')
gh_stats.to_csv(f'{NETID}_gh_stats.csv', sep=';')
pd.DataFrame(recent).to_csv(f'{NETID}_gh_recent_commits.csv', sep=';', index=False)
gh_stats

,gh_full_name,nstars,nforks,lastGHCommitDate,archived
project,,,,,
nickabattista_ib2d,nickabattista/IB2d,204,101,2026-06-14,False
cartavis_carta-frontend,CARTAvis/carta-frontend,19,15,2026-09-23,False
nanocomp_mpb,NanoComp/mpb,214,107,2026-05-27,False
kklmn_xrt,kklmn/xrt,101,39,2026-09-24,False
pytorch_audio,pytorch/audio,2945,799,2026-09-23,False
bernatgel_karyoploter,bernatgel/karyoploteR,377,43,2026-04-28,False
wandb_client,wandb/wandb,11259,899,2026-09-25,False
ohdsi_atlas,OHDSI/Atlas,323,154,2025-11-09,False
mummer4_mummer,mummer4/mummer,575,119,2025-02-04,False
nmslib_nmslib,nmslib/nmslib,3591,461,2026-01-12,False

## 6. Tables for the text cells below
Run this, then paste its output into the two markdown cells that follow.

In [ ]:
def md_table(df):
    cols = list(df.columns)
    lines = ['| ' + ' | '.join(cols) + ' |', '|' + '---|' * len(cols)]
    lines += ['| ' + ' | '.join(str(v) for v in row) + ' |' for row in df.itertuples(index=False)]
    return '\n'.join(lines)

print(md_table(gh_stats.reset_index()[['project', 'nstars', 'nforks', 'lastGHCommitDate']]))
print()
print(md_table(woc_stats.reset_index()[['project_wocid', 'ncommits', 'nauthors', 'min_time', 'min_date', 'max_time', 'max_date']]))

| project | nstars | nforks | lastGHCommitDate |
|---|---|---|---|
| nickabattista_ib2d | 204 | 101 | 2026-06-14 |
| cartavis_carta-frontend | 19 | 15 | 2026-09-23 |
| nanocomp_mpb | 214 | 107 | 2026-05-27 |
| kklmn_xrt | 101 | 39 | 2026-09-24 |
| pytorch_audio | 2945 | 799 | 2026-09-23 |
| bernatgel_karyoploter | 377 | 43 | 2026-04-28 |
| wandb_client | 11259 | 899 | 2026-09-25 |
| ohdsi_atlas | 323 | 154 | 2025-11-09 |
| mummer4_mummer | 575 | 119 | 2025-02-04 |
| nmslib_nmslib | 3591 | 461 | 2026-01-12 |

| project_wocid | ncommits | nauthors | min_time | min_date | max_time | max_date |
|---|---|---|---|---|---|---|
| bernatgel_karyoploter | 674 | 15 | 1444405906 | 2015-10-09 | 1749198667 | 2025-06-06 |
| cartavis_carta-frontend | 12474 | 76 | 1524835993 | 2018-04-27 | 1762270305 | 2025-11-04 |
| kklmn_xrt | 1591 | 12 | 1459266517 | 2016-03-29 | 1762357339 | 2025-11-05 |
| mummer4_mummer | 405 | 29 | 1352343979 | 2012-11-08 | 1739151225 | 2025-02-10 |
| nanocomp_mpb | 1335 | 35 | 895645130 | 1998-05-20 | 1775155248 | 2026-04-02 |
| nickabattista_ib2d | 994 | 28 | 1434499605 | 2015-06-17 | 1756008042 | 2025-08-24 |
| nmslib_nmslib | 1995 | 100 | 1373454367 | 2013-07-10 | 1776120170 | 2026-04-13 |
| ohdsi_atlas | 6636 | 139 | 1436372795 | 2015-07-08 | 1761750248 | 2025-10-29 |
| pytorch_audio | 15856 | 1513 | 1493944663 | 2017-05-05 | 1776253805 | 2026-04-15 |
| wandb_client | 54742 | 561 | 1487661941 | 2017-02-21 | 1762386331 | 2025-11-05 |

### GitHub info (stars, forks, last commit date)

_Paste the first table printed above here._

### World of Code info (commits, authors, min time, max time)

_Paste the second table printed above here._

Note: WoC data runs to about Jan 2025, so projects with later GitHub activity will show fewer commits in WoC than on GitHub.

# Make sure you check in to your fork not just the notebook but also the csv files!!!